def odk_users():
    return [
        {
            "id": "7",
            "displayName": "Collector",
            "email": "collector@odk.org",
            "type": "user",
            "createdAt": "2025-02-11T21:25:02.963-05:00",
            "updatedAt": None,
            "deletedAt": None,
        }
    ]


def odk_form_submission_attachments():
    return [{"name": "1739327186781.m4a", "exists": True}]


def odk_form_submissions():
    return {
        "value": [
            {
                "start": "2025-02-12T08:42:13.587-05:00",
                "end": "2025-02-12T08:42:42.959-05:00",
                "today": "2025-02-12",
                "community": "minura",
                "community_other": None,
                "local_ecosystem": "stable",
                "important_resources": "Furtei",
                "traditional_harvesting": "annually",
                "threats": "land_encroachment pollution climate_change mining",
                "threats_other": None,
                "migratory_species": "not_sure",
                "availability_resources": "decreasing",
                "abundance_indicator_species": "no",
                "traditional_ecological_knowledge": "elders_guidance apprenticeships schools_educational_institutions",
                "traditional_ecological_knowledge_other": None,
                "helpful_resources": "Gstanvi",
                "location": None,
                "photo": None,
                "audio": None,
                "meta": {"instanceID": "uuid:06ed309e-980c-45be-b52b-c1cd143d5d2d"},
                "__id": "uuid:06ed309e-980c-45be-b52b-c1cd143d5d2d",
                "__system": {
                    "submissionDate": "2025-02-12T13:42:43.273Z",
                    "updatedAt": None,
                    "submitterId": "7",
                    "submitterName": "Collector",
                    "attachmentsPresent": 0,
                    "attachmentsExpected": 0,
                    "status": None,
                    "reviewState": None,
                    "deviceId": "collect:88Lhh2JMAVd4PXdY",
                    "edits": 0,
                    "formVersion": "1",
                    "deletedAt": None,
                },
            },
            {
                "start": "2025-02-11T21:25:45.388-05:00",
                "end": "2025-02-11T21:26:28.668-05:00",
                "today": "2025-02-11",
                "community": "klanda",
                "community_other": None,
                "local_ecosystem": "declining",
                "important_resources": "Piorty",
                "traditional_harvesting": "monthly",
                "threats": "logging climate_change other",
                "threats_other": None,
                "migratory_species": "no",
                "availability_resources": "not_sure",
                "abundance_indicator_species": "no",
                "traditional_ecological_knowledge": "apprenticeships elders_guidance schools_educational_institutions",
                "traditional_ecological_knowledge_other": None,
                "helpful_resources": "Wayuio",
                "location": {
                    "type": "Point",
                    "coordinates": [-73.856824, 152.0195872, 41.599998],
                    "properties": {"accuracy": 20},
                },
                "audio": "1739327186781.m4a",
                "meta": {"instanceID": "uuid:24951a9e-db46-4e22-9bce-910377c9dd22"},
                "__id": "uuid:24951a9e-db46-4e22-9bce-910377c9dd22",
                "__system": {
                    "submissionDate": "2025-02-12T02:26:29.206Z",
                    "updatedAt": None,
                    "submitterId": "7",
                    "submitterName": "Collector",
                    "attachmentsPresent": 1,
                    "attachmentsExpected": 1,
                    "status": None,
                    "reviewState": None,
                    "deviceId": "collect:88Lhh2JMAVd4PXdY",
                    "edits": 0,
                    "formVersion": "1",
                    "deletedAt": None,
                },
            },
            {
                "start": "2025-02-11T21:25:02.963-05:00",
                "end": "2025-02-11T21:25:42.741-05:00",
                "today": "2025-02-11",
                "community": "iriva",
                "community_other": None,
                "local_ecosystem": "declining",
                "important_resources": "Herta",
                "traditional_harvesting": "annually",
                "threats": "climate_change land_encroachment logging",
                "threats_other": None,
                "migratory_species": "no",
                "availability_resources": "increasing",
                "abundance_indicator_species": "not_sure",
                "traditional_ecological_knowledge": "elders_guidance apprenticeships",
                "traditional_ecological_knowledge_other": None,
                "helpful_resources": "Rivana",
                "location": {
                    "type": "Point",
                    "coordinates": [-77.9867385, 40.322394, 41.599998],
                    "properties": {"accuracy": 12.399},
                },
                "meta": {"instanceID": "uuid:cb7955d8-dc7c-480f-9699-20555a155c92"},
                "__id": "uuid:cb7955d8-dc7c-480f-9699-20555a155c92",
                "__system": {
                    "submissionDate": "2025-02-12T02:25:43.495Z",
                    "updatedAt": None,
                    "submitterId": "7",
                    "submitterName": "Collector",
                    "attachmentsPresent": 0,
                    "attachmentsExpected": 0,
                    "status": None,
                    "reviewState": None,
                    "deviceId": "collect:88Lhh2JMAVd4PXdY",
                    "edits": 0,
                    "formVersion": "1",
                    "deletedAt": None,
                },
            },
        ]
    }
