version: 2.1



workflows:
  run-tests:
    jobs:
      - test

jobs:
  test:
    resource_class: medium
    docker:
      - image: cimg/python:3.11.10

    steps:
      - checkout
      - run:
          name: Install PostgreSQL server to test against
          command: |
            sudo apt-get update && sudo apt-get install --yes postgresql
      - run:
          name: Install tox for Python 3.11
          command: |
            python -m pip install --upgrade "pip>=26.1"
            pip install tox~=4.18
      - run:
          name: Run tests
          command: tox -p 3 -- -v
          environment:
            PIP_UPLOADED_PRIOR_TO: P7D
