version: 2.1

orbs:
  python: circleci/python@3.0.0

workflows:
  run-tests:
    jobs:
      - test

jobs:
  test:
    executor:
      name: python/default
      tag: "3.13"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: ""
          args: tox~=4.18
          pypi-cache: false
      - run:
          name: Run tests
          command: tox -- -v
