version: 2.1

orbs:
  python: circleci/python@3.0.0

executors:
  machine-executor:
    machine:
      # https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
      image: ubuntu-2404:current

workflows:
  run-tests:
    jobs:
      - test

jobs:
  test:
    resource_class: medium
    # machine executor is required to expose ports in tox-docker:
    # https://circleci.com/docs/2.0/building-docker-images/#mounting-folders
    executor: machine-executor

    steps:
      - checkout
      - run:
          # If we want to get rid of this step, convert our scripts to use
          # SqlAlchemy so tests would use SQLite.
          name: Install PostgreSQL server to test against
          command: |
            sudo apt-get update && sudo apt-get install --yes postgresql
      - run:
          # We set Python 3.11 as the default version for CircleCI because it's the
          # version we use for our Windmill instances (as "latest stable").
          # Additionally, any tests for scripts that use the Azure Storage Blob SDK
          # fail on CircleCI with Python 3.13, even though the scripts run fine in
          # Windmill runtime with 3.13.
          # TODO: Figure out why the Azure Storage Blob SDK fails on CircleCI with 3.13
          name: Install and set Python 3.11
          command: |
            pyenv install 3.11.10
            pyenv global 3.11.10
      - run:
          name: Install tox for Python 3.11
          command: |
            python -m pip install --upgrade pip
            pip install tox~=4.18 tox-docker~=5.0
      - run:
          name: Run tests
          command: tox -- -v
