version: 2.1

orbs:
  python: circleci/python@3.0.0

workflows:
  run-tests:
    jobs:
      - test

jobs:
  test:
    executor:
      name: python/default
      tag: "3.13"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: ""
          args: tox~=4.18 tox-docker~=5.0
          pypi-cache: false
      - run:
          # If we want to get rid of this step, convert our scripts to use
          # SqlAlchemy so tests would use SQLite.
          name: Install PostgreSQL server to test against
          command: |
            sudo apt-get update && sudo apt-get install postgresql
      - run:
          name: Run tests
          command: tox -- -v
