summary: GC Local Contexts Annotations
value:
  css:
    buttoncomponent:
      button:
        class: ''
        style: ''
      container:
        class: ''
        style: ''
    checkboxcomponent:
      container:
        class: ''
        style: ''
      text:
        class: ''
        style: ''
    containercomponent:
      container:
        class: ''
        style: ''
    fileinputcomponent:
      container:
        class: ''
        style: ''
    formcomponent:
      button:
        class: ''
        style: ''
      container:
        class: ''
        style: ''
    steppercomponent:
      container:
        class: ''
        style: ''
    textcomponent:
      container:
        class: ''
        style: ''
      text:
        class: ''
        style: ''
  fullscreen: false
  grid:
    - '12':
        fixed: true
        fullHeight: false
        h: 1
        w: 8
        x: 2
        'y': 1
      '3':
        fixed: true
        fullHeight: false
        h: 1
        w: 1
        x: 0
        'y': 0
      id: pageTitle
      data:
        id: pageTitle
        type: textcomponent
        actions: []
        componentInput:
          type: templatev2
          connections: []
          eval: Guardian Connector Local Contexts Annotations
          fieldType: template
        configuration:
          copyButton:
            type: static
            value: false
          disableNoText:
            type: static
            value: false
          style:
            type: static
            value: Title
          tooltip:
            type: static
            value: ''
        customCss:
          container:
            class: ''
            style: ''
          text:
            class: ''
            style: ''
        horizontalAlignment: center
        verticalAlignment: top
    - '12':
        fixed: false
        fullHeight: false
        h: 1
        w: 8
        x: 2
        'y': 3
      '3':
        fixed: false
        fullHeight: false
        h: 1
        w: 1
        x: 1
        'y': 6
      id: formTitle
      data:
        id: formTitle
        type: textcomponent
        actions: []
        componentInput:
          type: templatev2
          connections: []
          eval: "\U0001F3F7️ Apply Local Contexts labels to a dataset"
          fieldType: template
        configuration:
          copyButton:
            type: static
            value: false
          disableNoText:
            type: static
            value: false
          style:
            type: static
            value: Subtitle
          tooltip:
            type: static
            value: ''
        customCss:
          container:
            class: ''
            style: ''
          text:
            class: ''
            style: ''
        horizontalAlignment: center
        verticalAlignment: top
    - '12':
        fixed: true
        fullHeight: false
        h: 15
        w: 8
        x: 2
        'y': 5
      '3':
        fixed: true
        fullHeight: false
        h: 8
        w: 2
        x: 1
        'y': 7
      id: formStepper
      data:
        id: formStepper
        type: steppercomponent
        actions: []
        componentInput:
          type: runnable
          autoRefresh: false
          fields: {}
          fieldType: any
          recomputeOnInputChanged: false
          runnable:
            name: 0 Form stepper validations
            inlineScript:
              content: '!inline 0_form_stepper_validations.inline_script.frontend.js'
              language: frontend
              path: f/apps/local_contexts/0_Form_stepper_validations
              suggestedRefreshOn:
                - id: state
                  key: dataset
        configuration: {}
        customCss:
          container:
            class: border-2 border-blue-300 border-dashed
            style: ''
        numberOfSubgrids: 3
        onNext: []
        onPrevious: []
        tabs:
          - Select your dataset
          - Choose labels to apply
          - Finalize
    - '12':
        fixed: false
        fullHeight: false
        h: 1
        w: 8
        x: 2
        'y': 20
      '3':
        fixed: false
        fullHeight: false
        h: 2
        w: 1
        x: 1
        'y': 0
      id: linkToDocumentation
      data:
        id: linkToDocumentation
        type: htmlcomponent
        componentInput:
          type: templatev2
          connections: []
          eval: >-
            <center><em>Need help? Visit our <a
            href="https://docs.guardianconnector.net/reference/gc-toolkit/gc-scripts-hub/dataset-uploader"
            target="_blank">documentation website</a>.</em></center>
          fieldType: template
        configuration: {}
        customCss:
          container:
            class: ''
            style: ''
  hiddenInlineScripts:
    - name: 0 Fetch tables from Postgres
      autoRefresh: true
      fields:
        db:
          type: static
          value: '$res:f/connectors/postgresql'
          fieldType: object
          format: resource-postgresql
      inlineScript:
        content: '!inline 0_fetch_tables_from_postgres.inline_script.py'
        lock: '!inline 0_fetch_tables_from_postgres.inline_script.lock'
        language: python3
        path: f/apps/local_contexts/0_Fetch_tables_from_Postgres
        schema:
          $schema: 'https://json-schema.org/draft/2020-12/schema'
          type: object
          properties:
            db:
              type: object
              description: ''
              default: null
              format: resource-postgresql
          required:
            - db
      recomputeIds: []
      recomputeOnInputChanged: false
      transformer:
        content: |-
          state.tables = Object.values(result)
            // Remove tables that end with internal suffixes we don’t want to show
            .filter(name =>
              !name.endsWith("__columns") &&
              !name.endsWith("__labels") &&
              !name.endsWith("__metadata")
            )
            // Remove local contexts tables
            .filter(name =>
              !name.includes("localcontexts")
            )
            // Sort remaining table names alphabetically
            .sort((a, b) => a.localeCompare(b))
        language: frontend
        path: f/apps/local_contexts/Transformer
        suggestedRefreshOn:
          - id: state
            key: tables
    - name: 1 Set dataset
      autoRefresh: false
      fields: {}
      inlineScript:
        content: '!inline 1_set_dataset.inline_script.frontend.js'
        language: frontend
        path: f/apps/local_contexts/1_Set_dataset
        refreshOn:
          - id: selectTable
            key: result
        suggestedRefreshOn:
          - id: state
            key: dataset
      recomputeIds: []
      recomputeOnInputChanged: true
    - type: inline
      name: Background Runnable 2
      fields: {}
      hidden: true
  hideLegacyTopBar: true
  mobileViewOnSmallerScreens: false
  norefreshbar: false
  subgrids:
    formStepper-0:
      - '12':
          fixed: false
          fullHeight: false
          h: 3
          w: 10
          x: 1
          'y': 3
        '3':
          fixed: false
          fullHeight: false
          h: 2
          w: 1
          x: 2
          'y': 0
        id: a
        data:
          id: a
          type: htmlcomponent
          componentInput:
            type: templatev2
            connections: []
            eval: |-
              <h5 class="text-[16px] font-semibold text-gray-800 mb-1">
                Select a dataset<span class="text-red-500">*</span>
              </h5>

              <p class="text-sm text-gray-500 leading-relaxed">
                Select a dataset you wish to annotate using <a href="https://localcontexts.org/" target="_blank">Local Contexts</a> labels. 
                <em>Note: datasets are tables in your data warehouse.</em>
              </p>
            fieldType: template
          configuration: {}
          customCss:
            container:
              class: ''
              style: ''
      - '12':
          fixed: false
          fullHeight: false
          h: 1
          w: 10
          x: 1
          'y': 6
        '3':
          fixed: false
          fullHeight: false
          h: 1
          w: 2
          x: 0
          'y': 0
        id: selectTable
        data:
          id: selectTable
          type: selectcomponent
          configuration:
            create:
              type: static
              value: false
            defaultValue:
              type: static
            disabled:
              type: static
              value: false
            fullWidth:
              type: static
              value: true
            items:
              type: evalv2
              value: []
              connections:
                - id: tables
                  componentId: state
              expr: state.tables
            nativeHtmlSelect:
              type: static
              value: false
            placeholder:
              type: static
              value: Select a dataset
            preselectFirst:
              type: static
              value: false
          customCss:
            input:
              class: ''
              style: ''
          verticalAlignment: center
    formStepper-1: []
    formStepper-2:
      - '12':
          fixed: true
          fullHeight: false
          h: 1
          w: 12
          x: 0
          'y': 1
        '3':
          fixed: true
          fullHeight: false
          h: 1
          w: 1
          x: 0
          'y': 0
        id: finalizeTitle
        data:
          id: finalizeTitle
          type: textcomponent
          actions: []
          componentInput:
            type: templatev2
            connections: []
            eval: "\U0001F4C4 Review summary"
            fieldType: template
          configuration:
            copyButton:
              type: static
              value: false
            disableNoText:
              type: static
              value: false
            style:
              type: static
              value: Body
            tooltip:
              type: static
              value: ''
          customCss:
            container:
              class: ''
              style: ''
            text:
              class: font-bold
              style: ''
          horizontalAlignment: center
          verticalAlignment: top
      - '12':
          fixed: false
          fullHeight: false
          h: 1
          w: 3
          x: 1
          'y': 2
        '3':
          fixed: false
          fullHeight: false
          h: 1
          w: 1
          x: 1
          'y': 0
        id: datasetNameLabel
        data:
          id: datasetNameLabel
          type: textcomponent
          actions: []
          componentInput:
            type: templatev2
            connections: []
            eval: 'Dataset name:'
            fieldType: template
          configuration:
            copyButton:
              type: static
              value: false
            disableNoText:
              type: static
              value: false
            style:
              type: static
              value: Body
            tooltip:
              type: static
              value: ''
          customCss:
            container:
              class: ''
              style: ''
            text:
              class: font-bold
              style: ''
          horizontalAlignment: left
          verticalAlignment: top
      - '12':
          fixed: true
          fullHeight: false
          h: 1
          w: 7
          x: 4
          'y': 2
        '3':
          fixed: true
          fullHeight: false
          h: 1
          w: 1
          x: 2
          'y': 0
        id: datasetName
        data:
          id: datasetName
          type: textcomponent
          actions: []
          componentInput:
            type: evalv2
            connections:
              - id: datasetName
                componentId: state
            eval: '${selectFile.result[0].name}'
            expr: state.datasetName
            fieldType: template
          configuration:
            copyButton:
              type: static
              value: false
            disableNoText:
              type: static
              value: false
            style:
              type: static
              value: Body
            tooltip:
              type: static
              value: ''
          customCss:
            container:
              class: 'bg-gray-100 dark:bg-gray-800'
              style: ''
            text:
              class: ''
              style: ''
          horizontalAlignment: left
          verticalAlignment: top
      - '12':
          fixed: false
          fullHeight: false
          h: 1
          w: 2
          x: 5
          'y': 7
        '3':
          fixed: false
          fullHeight: false
          h: 1
          w: 1
          x: 1
          'y': 2
        id: saveAndFinishButton
        data:
          id: saveAndFinishButton
          type: buttoncomponent
          actions: []
          componentInput:
            type: runnable
            autoRefresh: false
            fields: {}
            fieldType: any
            recomputeOnInputChanged: false
          configuration:
            afterIcon:
              type: static
              value: cloud-upload
            beforeIcon:
              type: static
              value: ''
            color:
              type: static
              value: dark
            confirmationModal:
              type: oneOf
              configuration:
                none: {}
              selected: none
            disabled:
              type: evalv2
              value: false
              connections:
                - id: newColumns
                  componentId: state
                - id: newRows
                  componentId: state
                - id: finalizeSuccess
                  componentId: state
              expr: >-
                state.finalizeSuccess || !(state.newRows > 0 && state.newColumns
                > 0)
            fillContainer:
              type: static
              value: false
            label:
              type: static
              value: Save & Finish
            onError:
              type: oneOf
              configuration:
                errorOverlay: {}
              selected: errorOverlay
            onSubmit:
              type: oneOf
              configuration:
                none: {}
              selected: none
            onSuccess:
              type: oneOf
              configuration:
                none: {}
              selected: none
            runInBackground:
              type: static
              value: false
            size:
              type: static
              value: xs
            tooltip:
              type: static
            triggerOnAppLoad:
              type: static
              value: false
          customCss:
            button:
              class: ''
              style: ''
            container:
              class: ''
              style: ''
          horizontalAlignment: center
          recomputeIds: []
          verticalAlignment: center
      - '12':
          fixed: false
          fullHeight: false
          h: 2
          w: 10
          x: 1
          'y': 8
        '3':
          fixed: false
          fullHeight: false
          h: 1
          w: 1
          x: 0
          'y': 3
        id: saveResult
        data:
          id: saveResult
          type: textcomponent
          actions: []
          componentInput:
            type: runnable
            autoRefresh: true
            connections: []
            eval: ''
            expr: ''
            fields: {}
            fieldType: template
            hideRefreshButton: true
            recomputeOnInputChanged: true
          configuration:
            copyButton:
              type: static
              value: false
            disableNoText:
              type: static
              value: true
            style:
              type: static
              value: Label
            tooltip:
              type: static
              value: ''
          customCss:
            container:
              class: ''
              style: ''
            text:
              class: ''
              style: ''
          horizontalAlignment: center
          verticalAlignment: center
      - '12':
          fixed: false
          fullHeight: false
          h: 1
          w: 10
          x: 1
          'y': 10
        '3':
          fixed: false
          fullHeight: false
          h: 1
          w: 1
          x: 2
          'y': 2
        id: saveLabel
        data:
          id: saveLabel
          type: textcomponent
          actions: []
          componentInput:
            type: runnable
            autoRefresh: true
            connections: []
            eval: ✍️ Ready to write this dataset to your warehouse?
            fields: {}
            fieldType: template
            hideRefreshButton: true
            recomputeOnInputChanged: true
          configuration:
            copyButton:
              type: static
              value: false
            disableNoText:
              type: static
              value: true
            style:
              type: static
              value: Body
            tooltip:
              type: static
              value: ''
          customCss:
            container:
              class: ''
              style: ''
            text:
              class: |-
                italic 
                text-sm
              style: ''
          horizontalAlignment: center
          verticalAlignment: center
  theme:
    type: inlined
    css: ''
  unusedInlineScripts: []
