SAMPLE_PROJECT = {
    "unique_id": "1d220c8c-1a9b-449c-a3d8-2baf48491336",
    "external_ids": {
        "providers_id": None,
        "publication_doi": None,
        "project_data_guid": None,
    },
    "source_project_uuid": None,
    "project_page": "https://sandbox.localcontextshub.org/projects/1d220c8c-1a9b-449c-a3d8-2baf48491336",
    "title": "Guardian Connector LC labels",
    "description": "Local Contexts labels for Guardian Connector",
    "project_type": "Collection",
    "project_contact": {"name": "John Doe", "email": "john.doe@example.com"},
    "urls": [],
    "project_privacy": "Contributor",
    "date_added": "2026-02-09T20:35:29.519523Z",
    "date_modified": "2026-02-09T20:47:35.279601Z",
    "created_by": [
        {
            "institution": None,
            "researcher": None,
            "community": {
                "id": 118,
                "name": "My Community",
                "profile_url": "https://sandbox.localcontextshub.org/communities/view/118/",
            },
        }
    ],
    "contributors": {
        "institutions": [],
        "communities": [
            {
                "id": 118,
                "name": "My Community",
                "profile_url": "https://sandbox.localcontextshub.org/communities/view/118/",
            }
        ],
        "researchers": [],
        "hub_users": [],
        "others": [],
    },
    "notice": [],
    "bc_labels": [
        {
            "unique_id": "e84a996a-6c71-4a68-a057-e59188fb9cec",
            "label_page": "https://sandbox.localcontextshub.org/labels/e84a996a-6c71-4a68-a057-e59188fb9cec/",
            "name": "BC Clan (BC CL)",
            "label_type": "clan",
            "language_tag": "en",
            "language": "English",
            "label_text": "This Label is being used to indicate that this material is traditionally and usually not publicly available. The Label lets future users know that this data has specific conditions for use and sharing because of clan membership and/or relationships. This Label asks viewers of this data to respect the cultural values and expectations about circulation and use defined by designated clans, members, and their internal relations.",
            "img_url": "https://localcontexts.org/wp-content/uploads/2025/04/bc-clan.png",
            "svg_url": None,
            "audiofile": None,
            "community": {
                "id": 118,
                "name": "My Community",
                "profile_url": "https://sandbox.localcontextshub.org/communities/view/118/",
            },
            "translations": [],
            "created": "2026-02-09T20:40:11.357426Z",
            "updated": "2026-02-09T20:43:56.343750Z",
        },
        {
            "unique_id": "00909459-882f-49eb-9b9e-8e3ef17a44b1",
            "label_page": "https://sandbox.localcontextshub.org/labels/00909459-882f-49eb-9b9e-8e3ef17a44b1/",
            "name": "BC Provenance (BC P)",
            "label_type": "provenance",
            "language_tag": "en",
            "language": "English",
            "label_text": "This Label is being used to affirm an inherent interest Indigenous people have in the scientific collections and data about communities, peoples, and the biodiversity found within traditional lands, waters and territories. [Community name or authorizing party] retains the right to be named and associated with it into the future. This association reflects a significant relationship and responsibility to [the species or biological entity] and associated scientific collections and data. [Optional attribution statement]",
            "img_url": "https://localcontexts.org/wp-content/uploads/2025/04/bc-provenance.png",
            "svg_url": None,
            "audiofile": None,
            "community": {
                "id": 118,
                "name": "My Community",
                "profile_url": "https://sandbox.localcontextshub.org/communities/view/118/",
            },
            "translations": [],
            "created": "2026-02-09T20:38:02.263213Z",
            "updated": "2026-02-09T20:44:01.148090Z",
        },
        {
            "unique_id": "862c6e0c-5555-454c-b25a-9854cb9d1851",
            "label_page": "https://sandbox.localcontextshub.org/labels/862c6e0c-5555-454c-b25a-9854cb9d1851/",
            "name": "BC Consent Verified (BC CV)",
            "label_type": "consent_verified",
            "language_tag": "en",
            "language": "English",
            "label_text": "This Label is being used to verify that [community name or authorizing party] have consent conditions in place for the use of this information, collections, data, and digital sequence information. [These can be found at ….].",
            "img_url": "https://localcontexts.org/wp-content/uploads/2025/04/bc-consent-verified.png",
            "svg_url": None,
            "audiofile": None,
            "community": {
                "id": 118,
                "name": "My Community",
                "profile_url": "https://sandbox.localcontextshub.org/communities/view/118/",
            },
            "translations": [],
            "created": "2026-02-09T20:37:52.722201Z",
            "updated": "2026-02-09T20:44:16.401314Z",
        },
    ],
    "tk_labels": [
        {
            "unique_id": "73d43de7-172c-450b-808a-12c32c252a8d",
            "label_page": "https://sandbox.localcontextshub.org/labels/73d43de7-172c-450b-808a-12c32c252a8d/",
            "name": "TK Secret / Sacred (TK SS)",
            "label_type": "secret_sacred",
            "language_tag": "en",
            "language": "English",
            "label_text": "This Label is being used to indicate that this material is traditionally and usually not publicly available because it contains important secret or sacred components. The Label is correcting a misunderstanding about the significance of this material and therefore its circulation conditions. It is letting users know that because of its secret/sacred status it is not, and was never free, public, or available for everyone at anytime. This Label asks you to think about whether you should be using this material and to respect different cultural values and expectations about circulation and use.",
            "img_url": "https://localcontexts.org/wp-content/uploads/2025/04/tk-secret-sacred.png",
            "svg_url": None,
            "audiofile": None,
            "community": {
                "id": 118,
                "name": "My Community",
                "profile_url": "https://sandbox.localcontextshub.org/communities/view/118/",
            },
            "translations": [],
            "created": "2026-02-09T20:39:41.720026Z",
            "updated": "2026-02-09T20:44:05.617610Z",
        },
        {
            "unique_id": "583aeb2b-cad8-48e8-ae0c-9fe9d1d64a24",
            "label_page": "https://sandbox.localcontextshub.org/labels/583aeb2b-cad8-48e8-ae0c-9fe9d1d64a24/",
            "name": "TK Community Voice (TK CV)",
            "label_type": "community_voice",
            "language_tag": "en",
            "language": "English",
            "label_text": "This Label is being used to encourage the sharing of stories and voices about this material. The Label indicates that existing knowledge or descriptions are incomplete or partial. Any community member is invited and welcome to contribute to our community knowledge about this event, photograph, recording or heritage item. Sharing our voices helps us reclaim our histories and knowledge. This sharing is an internal process.",
            "img_url": "https://localcontexts.org/wp-content/uploads/2025/04/tk-community-voice.png",
            "svg_url": None,
            "audiofile": None,
            "community": {
                "id": 118,
                "name": "My Community",
                "profile_url": "https://sandbox.localcontextshub.org/communities/view/118/",
            },
            "translations": [
                {
                    "translated_name": "Voz da Comunidade TK (TK CV)",
                    "language_tag": "pt",
                    "language": "Portuguese",
                    "translated_text": "Este selo está sendo usado para incentivar o compartilhamento de histórias e perspectivas sobre este material. O selo indica que o conhecimento ou as descrições existentes são incompletos ou parciais. Qualquer membro da comunidade está convidado a contribuir para o conhecimento coletivo sobre este evento, fotografia, gravação ou item de patrimônio cultural. Compartilhar nossas vozes nos ajuda a resgatar nossas histórias e nosso conhecimento. Esse compartilhamento é um processo interno.",
                }
            ],
            "created": "2026-02-09T20:37:39.508754Z",
            "updated": "2026-02-09T20:43:36.459434Z",
        },
        {
            "unique_id": "cba016a8-0e50-4402-95d5-9176a60b24eb",
            "label_page": "https://sandbox.localcontextshub.org/labels/cba016a8-0e50-4402-95d5-9176a60b24eb/",
            "name": "TK Attribution (TK A)",
            "label_type": "attribution",
            "language_tag": "en",
            "language": "English",
            "label_text": "This Label is being used to correct historical mistakes or exclusions pertaining to this material. This is especially in relation to the names of the people involved in performing or making this work and/or correctly naming the community from which it originally derives. As a user you are being asked to also apply the correct attribution in any future use of this work.",
            "img_url": "https://localcontexts.org/wp-content/uploads/2025/04/tk-attribution.png",
            "svg_url": None,
            "audiofile": None,
            "community": {
                "id": 118,
                "name": "My Community",
                "profile_url": "https://sandbox.localcontextshub.org/communities/view/118/",
            },
            "translations": [],
            "created": "2026-02-09T20:36:48.517552Z",
            "updated": "2026-02-09T20:43:45.383105Z",
        },
    ],
    "sub_projects": [],
    "related_projects": [],
    "project_boundary_geojson": None,
}
