SAMPLE_PROJECT = {
    "unique_id": "fake0000-0000-0000-0000-000000000001",
    "external_ids": {
        "providers_id": None,
        "publication_doi": None,
        "project_data_guid": None,
    },
    "source_project_uuid": None,
    "project_page": "https://sandbox.localcontextshub.org/projects/fake0000-0000-0000-0000-000000000001",
    "title": "Guardian Connector LC labels",
    "description": "Local Contexts labels for Guardian Connector",
    "project_type": "Collection",
    "project_contact": {"name": "John Doe", "email": "john.doe@example.com"},
    "urls": [],
    "project_privacy": "Contributor",
    "date_added": "2026-02-09T20:35:29.519523Z",
    "date_modified": "2026-02-09T20:47:35.279601Z",
    "created_by": [
        {
            "institution": None,
            "researcher": None,
            "community": {
                "id": 118,
                "name": "My Community",
                "profile_url": "https://sandbox.localcontextshub.org/communities/view/118/",
            },
        }
    ],
    "contributors": {
        "institutions": [],
        "communities": [
            {
                "id": 118,
                "name": "My Community",
                "profile_url": "https://sandbox.localcontextshub.org/communities/view/118/",
            }
        ],
        "researchers": [],
        "hub_users": [],
        "others": [],
    },
    "notice": [],
    "bc_labels": [
        {
            "unique_id": "bc000000-0000-0000-0000-000000000001",
            "label_page": "https://sandbox.localcontextshub.org/labels/bc000000-0000-0000-0000-000000000001/",
            "name": "BC Provenance (BC P)",
            "label_type": "provenance",
            "language_tag": "en",
            "language": "English",
            "label_text": "This Label is being used to affirm an inherent interest Indigenous people have in the scientific collections and data about communities, peoples, and the biodiversity found within traditional lands, waters and territories. [Community name or authorizing party] retains the right to be named and associated with it into the future. This association reflects a significant relationship and responsibility to [the species or biological entity] and associated scientific collections and data. [Optional attribution statement]",
            "img_url": "https://localcontexts.org/wp-content/uploads/2025/04/bc-provenance.png",
            "svg_url": None,
            "audiofile": None,
            "community": {
                "id": 118,
                "name": "My Community",
                "profile_url": "https://sandbox.localcontextshub.org/communities/view/118/",
            },
            "translations": [],
            "created": "2026-02-09T20:38:02.263213Z",
            "updated": "2026-02-09T20:44:01.148090Z",
        },
        {
            "unique_id": "bc000000-0000-0000-0000-000000000002",
            "label_page": "https://sandbox.localcontextshub.org/labels/bc000000-0000-0000-0000-000000000002/",
            "name": "BC Consent Verified (BC CV)",
            "label_type": "consent_verified",
            "language_tag": "en",
            "language": "English",
            "label_text": "This Label is being used to verify that [community name or authorizing party] have consent conditions in place for the use of this information, collections, data, and digital sequence information. [These can be found at ….].",
            "img_url": "https://localcontexts.org/wp-content/uploads/2025/04/bc-consent-verified.png",
            "svg_url": None,
            "audiofile": "https://storage.googleapis.com/local-context-hub-staging.appspot.com/communities/tklabel-audiofiles/FAKE_AUDIO_ID.mp3?Expires=9999999999&GoogleAccessId=fake-access-id%40example.iam.gserviceaccount.com&Signature=TotallyFakeSignature1234567890",
            "community": {
                "id": 118,
                "name": "My Community",
                "profile_url": "https://sandbox.localcontextshub.org/communities/view/118/",
            },
            "translations": [],
            "created": "2026-02-09T20:37:52.722201Z",
            "updated": "2026-02-09T20:44:16.401314Z",
        },
    ],
    "tk_labels": [
        {
            "unique_id": "tk000000-0000-0000-0000-000000000001",
            "label_page": "https://sandbox.localcontextshub.org/labels/tk000000-0000-0000-0000-000000000001/",
            "name": "TK Kultural Sensitif (TK KS)",
            "label_type": "culturally_sensitive",
            "language_tag": "srn",
            "language": "Sranan Tongo",
            "label_text": "Disi Label de meki sma sabi tak disi materyal abi kultural en/of historis sensi. Disi Label e aksi fu taki wan bun wroko nanga disi materyal te yu e teki en, e yus en, en e broko en gi tra sma, spesrasi te materyal de baka of de feni baka nanga komyuniti fu en grontapu. Na somu kaso, disi Label o meki yu sabi tak de abi spesrasi pinsi fu yus disi materyal disi yu musu kisi streti-streti fu komyuniti srefi.",
            "img_url": "https://localcontexts.org/wp-content/uploads/2025/04/tk-culturally-sensitive.png",
            "svg_url": None,
            "audiofile": None,
            "community": {
                "id": 118,
                "name": "My Community",
                "profile_url": "https://sandbox.localcontextshub.org/communities/view/118/",
            },
            "translations": [
                {
                    "translated_name": "TK Kulutuwano Sensitipu (TK KS)",
                    "language_tag": "way",
                    "language": "Wayana",
                    "translated_text": "Nono etikëtï man enïlë, mëkïhpe nono materya man akë kulutura ëtëpï, amna istorï ëtëpï. Etikëtï man eputopï, nono man eputopï ihpë, eputopï man enïlë nono materya man ihpë, man eporï, man eipï, man ehetopï, molï te nono materya man ëtëpï tïmëhka man tïlëpï nono komünïtï man. Nono etu akë, etikëtï man eputopï tak nono materya man eipï man ehetopï tïmëhka pïjai, nono komünïtï man akë man tïlëpï enïlë.",
                },
                {
                    "translated_name": "TK Nyenzo Nyeti Kitamaduni (TK NK)",
                    "language_tag": "sw",
                    "language": "Swahili (macrolanguage)",
                    "translated_text": "Lebo hii inatumika kuonyesha kwamba nyenzo hii ina hisia za kitamaduni na/au kihistoria. Lebo hii inaomba utunzaji na uangalifu zichukuliwe wakati nyenzo hii inapofikiwa, inapotumiwa, na inaposambazwa, hasa pale nyenzo zinaporejeshwa au kuunganishwa tena na jamii za asili. Katika baadhi ya matukio, Lebo hii itaonyesha kwamba ruhusa maalum za kutumia nyenzo hii zinahitajika moja kwa moja kutoka kwa jamii husika.",
                },
            ],
            "created": "2026-02-10T02:01:47.228618Z",
            "updated": "2026-02-10T02:02:00.230130Z",
        },
        {
            "unique_id": "tk000000-0000-0000-0000-000000000002",
            "label_page": "https://sandbox.localcontextshub.org/labels/tk000000-0000-0000-0000-000000000002/",
            "name": "TK Community Voice (TK CV)",
            "label_type": "community_voice",
            "language_tag": "en",
            "language": "English",
            "label_text": "This Label is being used to encourage the sharing of stories and voices about this material. The Label indicates that existing knowledge or descriptions are incomplete or partial. Any community member is invited and welcome to contribute to our community knowledge about this event, photograph, recording or heritage item. Sharing our voices helps us reclaim our histories and knowledge. This sharing is an internal process.",
            "img_url": "https://localcontexts.org/wp-content/uploads/2025/04/tk-community-voice.png",
            "svg_url": None,
            "audiofile": None,
            "community": {
                "id": 118,
                "name": "My Community",
                "profile_url": "https://sandbox.localcontextshub.org/communities/view/118/",
            },
            "translations": [
                {
                    "translated_name": "Voz da Comunidade TK (TK CV)",
                    "language_tag": "pt",
                    "language": "Portuguese",
                    "translated_text": "Este selo está sendo usado para incentivar o compartilhamento de histórias e perspectivas sobre este material. O selo indica que o conhecimento ou as descrições existentes são incompletos ou parciais. Qualquer membro da comunidade está convidado a contribuir para o conhecimento coletivo sobre este evento, fotografia, gravação ou item de patrimônio cultural. Compartilhar nossas vozes nos ajuda a resgatar nossas histórias e nosso conhecimento. Esse compartilhamento é um processo interno.",
                }
            ],
            "created": "2026-02-09T20:37:39.508754Z",
            "updated": "2026-02-09T20:43:36.459434Z",
        },
        {
            "unique_id": "tk000000-0000-0000-0000-000000000003",
            "label_page": "https://sandbox.localcontextshub.org/labels/tk000000-0000-0000-0000-000000000003/",
            "name": "TK Attribution (TK A)",
            "label_type": "attribution",
            "language_tag": "en",
            "language": "English",
            "label_text": "This Label is being used to correct historical mistakes or exclusions pertaining to this material. This is especially in relation to the names of the people involved in performing or making this work and/or correctly naming the community from which it originally derives. As a user you are being asked to also apply the correct attribution in any future use of this work.",
            "img_url": "https://localcontexts.org/wp-content/uploads/2025/04/tk-attribution.png",
            "svg_url": None,
            "audiofile": None,
            "community": {
                "id": 118,
                "name": "My Community",
                "profile_url": "https://sandbox.localcontextshub.org/communities/view/118/",
            },
            "translations": [],
            "created": "2026-02-09T20:36:48.517552Z",
            "updated": "2026-02-09T20:43:45.383105Z",
        },
    ],
    "sub_projects": [],
    "related_projects": [],
    "project_boundary_geojson": None,
}
